import {Rule, SchematicContext, SchematicsException, Tree} from '@angular-devkit/schematics';
import {NodePackageInstallTask} from '@angular-devkit/schematics/tasks';
import {addDevPackageToPackageJson, addPackageToPackageJson, addScriptToPackageJson} from './package-config';
import {Schema} from './schema';

// Node Buffer (isyTranslation) is not supported in Browser context but schematics is executed with node and not with browser
/* eslint-disable @typescript-eslint/no-unsafe-assignment,@typescript-eslint/no-unsafe-member-access,@typescript-eslint/no-unsafe-argument,@typescript-eslint/no-unsafe-call */

interface ArchitectOptions {
  styles?: string[];
  assets?: (string | {input: string})[];
  tsConfig?: string;
}

interface MyBuild {
  options: ArchitectOptions;
  configurations?: {
    development?: {tsConfig?: string};
  };
}

interface MyTest {
  options: {
    tsConfig?: string;
  };
}

interface Architect {
  build: MyBuild;
  test?: MyTest;
}

interface ProjectInfo {
  projectType: string;
  root: string;
  sourceRoot: string;
  prefix?: string;
  architect: Architect;
}

interface Workspace {
  projects: {
    [key: string]: ProjectInfo;
  };
}

const ESLINT_CONFIG_PATH = '/eslint.config.js';
const ESLINT_BASE_CONFIG_PATH = '/eslint.config.base.js';
const GENERATED_ESLINT_MARKER = '// generated by @isyfact/isy-angular-widgets';
const PRETTIER_CONFIG_PATH = '/.prettierrc.js';
const PRETTIER_IGNORE_PATH = '/.prettierignore';

/**
 * Add necessary styles for isy-angular-widgets to the angular workspace.
 * @param workspace Current angular workspace object
 * @param context A rule factory, which is normally the way schematics are implemented. Returned by the tooling after loading a schematic description
 * @param tree List of styles
 * @returns Tree Tree with styles
 */
function applyStylesToWorkspace(workspace: Workspace, context: SchematicContext, tree: Tree): Tree {
  const styles = [
    'node_modules/primeicons/primeicons.css',
    'node_modules/primeflex/primeflex.min.css',
    'node_modules/@isyfact/isy-angular-widgets/assets/theme/isyfact-theme.scss'
  ];
  const projects = workspace?.projects || {};
  let updatedProjects = 0;

  for (const key in projects) {
    const project = projects[key];

    if (project.projectType !== 'application') {
      continue;
    }

    if (!project?.architect?.build?.options) {
      context.logger.warn(`⚠ Skipping add styles: Missing architect configuration on project ${key}.`);
      continue;
    }

    if (project.architect.build.options.styles) {
      const concatStyles = project.architect.build.options.styles.concat(styles);
      project.architect.build.options.styles = [...new Set(concatStyles)];
    } else {
      project.architect.build.options.styles = styles;
    }

    updatedProjects++;
    context.logger.info(`√ Added isy-angular-widgets styles to project '${key}'.`);
  }

  if (updatedProjects === 0) {
    context.logger.warn('⚠ Skipping add styles: Workspace does not contain any project of type application.');
    return tree;
  }

  tree.overwrite('/angular.json', JSON.stringify(workspace, null, 2));
  return tree;
}

/**
 * Adds the specified assets path (`src/assets`) to the assets array of the first application project
 * found in the provided Angular workspace configuration. If the assets array does not exist, it is initialized.
 * If the assets path is already present, no changes are made.
 * @param workspace - The Angular workspace configuration object.
 * @param context - The schematic context used for logging and reporting.
 * @param tree - The virtual file system tree representing the project files.
 * @returns The updated virtual file system tree.
 */
function applyAssetsToWorkspace(workspace: Workspace, context: SchematicContext, tree: Tree): Tree {
  const assetsPath = 'src/assets';
  const projects = workspace?.projects || {};
  let updatedProjects = 0;

  for (const key in projects) {
    const project = projects[key];

    if (project.projectType !== 'application') {
      continue;
    }

    const buildOptions = project.architect?.build?.options;

    if (!buildOptions) {
      context.logger.warn(`⚠ Skipping assets update: Missing build options on project '${key}'.`);
      continue;
    }

    if (Array.isArray(buildOptions.assets)) {
      const hasAssets = buildOptions.assets.some((entry) =>
        typeof entry === 'string' ? entry === assetsPath : entry.input === assetsPath
      );

      if (!hasAssets) {
        buildOptions.assets.push(assetsPath);
        context.logger.info(`√ Added '${assetsPath}' to assets array of project '${key}'.`);
      }
    } else {
      buildOptions.assets = [assetsPath];
      context.logger.info(`√ Initialized assets array with '${assetsPath}' on project '${key}'.`);
    }

    updatedProjects++;
  }

  if (updatedProjects === 0) {
    context.logger.warn('⚠ Skipping assets update: No application project found.');
    return tree;
  }

  tree.overwrite('/angular.json', JSON.stringify(workspace, null, 2));
  return tree;
}

/**
 * Loads the angular workspace store in angular.json.
 * @param tree List with angular.json properties
 * @returns Workspace Part structure of angular.json file
 * @throws {SchematicsException} if workspace is not available
 */
function loadWorkspace(tree: Tree): Workspace {
  const workspaceConfig = tree.read('/angular.json');

  if (!workspaceConfig) {
    throw new SchematicsException('❌ Could not find Angular workspace configuration.');
  }

  return JSON.parse(workspaceConfig.toString()) as Workspace;
}

/**
 * Create new translation file or merge if one already exists.
 * @param context A rule factory, which is normally the way schematics are implemented. Returned by the tooling after loading a schematic description.
 * @param tree Tree with translation files
 * @param language the current language
 * @throws {SchematicsException} if translation file does not exist or is empty
 */
export function addTranslationFile(context: SchematicContext, tree: Tree, language: string): void {
  const isyTranslation = tree.read('./node_modules/@isyfact/isy-angular-widgets/assets/i18n/' + language);
  const translationFilePath = '/src/assets/i18n/' + language;

  if (!isyTranslation) {
    throw new SchematicsException('❌ Could not find isy-angular-widgets translation file.');
  }

  if (tree.exists(translationFilePath)) {
    const translation = tree.read(translationFilePath);

    if (!translation) throw new SchematicsException(`❌ Could not read directory ${translationFilePath}.`);

    let translationJson = JSON.parse(translation.toString('utf-8'));
    const isyTranslationJson = JSON.parse(isyTranslation.toString('utf-8'));

    if (translationJson) {
      translationJson = {...translationJson, ...isyTranslationJson};
      context.logger.info('√ Add language keys (de, en) for isy-angular-widgets to existing language files.');
    }

    const space = 2;
    tree.overwrite(translationFilePath, JSON.stringify(translationJson, null, space));
  } else {
    tree.create(translationFilePath, isyTranslation.toString('utf-8'));
    context.logger.info('√ Add language files (de, en) for isy-angular-widgets.');
  }
}

/**
 * Normalizes a workspace-relative path to a Tree path.
 * @param path Workspace-relative path
 * @returns Normalized path starting with "/"
 */
function normalizeWorkspacePath(path: string): string {
  return path.startsWith('/') ? path : `/${path}`;
}

/**
 * Returns the first existing candidate path from the workspace tree.
 * @param tree Virtual file tree
 * @param candidates Candidate paths relative to workspace root
 * @returns Existing path or null
 */
function resolveExistingPath(tree: Tree, candidates: string[]): string | null {
  for (const candidate of candidates) {
    if (tree.exists(normalizeWorkspacePath(candidate))) {
      return candidate;
    }
  }

  return null;
}

/**
 * Resolves the build tsconfig path for a project.
 * Uses angular.json first and falls back to common workspace paths.
 * @param project Project info
 * @param tree Virtual file tree
 * @returns tsconfig path or null
 */
function getBuildTsConfigPath(project: ProjectInfo, tree: Tree): string | null {
  const configuredBuildTsConfig =
    project.architect?.build?.options?.tsConfig ?? project.architect?.build?.configurations?.development?.tsConfig;

  if (configuredBuildTsConfig) {
    return configuredBuildTsConfig;
  }

  const projectRoot = project.root ? `${project.root}/` : '';

  return resolveExistingPath(tree, [`${projectRoot}tsconfig.app.json`, 'tsconfig.app.json']);
}

/**
 * Resolves the test tsconfig path for a project.
 * Uses angular.json first and falls back to common workspace paths.
 * @param project Project info
 * @param tree Virtual file tree
 * @returns tsconfig path or null
 */
function getTestTsConfigPath(project: ProjectInfo, tree: Tree): string | null {
  const configuredTestTsConfig = project.architect?.test?.options?.tsConfig;

  if (configuredTestTsConfig) {
    return configuredTestTsConfig;
  }

  const projectRoot = project.root ? `${project.root}/` : '';

  return resolveExistingPath(tree, [`${projectRoot}tsconfig.spec.json`, 'tsconfig.spec.json']);
}

/**
 * Determines whether the workspace is a monorepo (multiple projects each with their own subdirectory)
 * or a simple single-app project (root project located at the workspace root).
 * @param workspace The angular workspace configuration
 * @returns true if the workspace is a monorepo
 */
function isMonorepo(workspace: Workspace): boolean {
  return Object.values(workspace.projects).every((project) => project.root !== '');
}

/**
 * Generates JS code that merges all rule objects from configs.test.
 * This avoids applying the test config globally without project-aware parserOptions.
 * @returns JavaScript source string for merged test rules
 */
function generateMergedTestRulesExpression(): string {
  return `
        ...Object.assign(
          {},
          ...configs.test
            .filter((config) => config && typeof config === 'object' && config.rules)
            .map((config) => config.rules)
        )`;
}

/**
 * Generates a TypeScript/HTML config block for a single project to be embedded in eslint.config.js.
 * @param name Project name
 * @param project Project info
 * @returns JavaScript source string for the config blocks
 */
function generateProjectConfigBlock(name: string, project: ProjectInfo, tree: Tree): string {
  const sourceRoot = project.sourceRoot || `src`;
  const prefix = project.prefix || 'app';

  const buildTsConfig = getBuildTsConfigPath(project, tree);
  const testTsConfig = getTestTsConfigPath(project, tree) ?? buildTsConfig;

  const buildProjectList = buildTsConfig ? `'${buildTsConfig}'` : '';
  const testProjectList = testTsConfig ? `'${testTsConfig}'` : '';

  const mergedTestRules = generateMergedTestRulesExpression();

  return `
    // ${name}: TS
    {
      files: ['${sourceRoot}/**/*.ts'],
      ignores: ['${sourceRoot}/**/*.spec.ts'],
      languageOptions: {
        parser: tsParser,
        parserOptions: {
          project: [${buildProjectList}],
          tsconfigRootDir: __dirname,
          sourceType: 'module'
        }
      },
      plugins: {'@angular-eslint': angular},
      rules: {
        ...angular.configs.recommended.rules,
        '@angular-eslint/directive-selector': ['error', {type: 'attribute', prefix: '${prefix}', style: 'camelCase'}],
        '@angular-eslint/component-selector': ['error', {type: 'element', prefix: '${prefix}', style: 'kebab-case'}]
      }
    },
    // ${name}: Spec TS
    {
      files: ['${sourceRoot}/**/*.spec.ts'],
      languageOptions: {
        parser: tsParser,
        parserOptions: {
          project: [${testProjectList}],
          tsconfigRootDir: __dirname,
          sourceType: 'module'
        }
      },
      plugins: {'@angular-eslint': angular},
      rules: {
      ${mergedTestRules}
      }
    },
    // ${name}: HTML
    {
      files: ['${sourceRoot}/**/*.html'],
      languageOptions: {parser: angularTemplateParser},
      plugins: {'@angular-eslint/template': angularTemplate},
      rules: {...angularTemplate.configs.recommended.rules}
    },
    // ${name}: Inline Templates
    {
      files: ['${sourceRoot}/**/*.component.ts'],
      plugins: {
        '@angular-eslint': angular,
        '@angular-eslint/template': angularTemplate
      },
      processor: angularTemplate.processors['extract-inline-html']
    }`;
}

/**
 * Generates the content for eslint.config.js based on the workspace structure.
 * Supports both simple Angular projects and monorepos.
 * @param workspace The angular workspace configuration
 * @returns The content of the eslint.config.js file as a string
 */
function generateEslintConfigContent(workspace: Workspace, tree: Tree): string {
  const projectEntries = Object.entries(workspace.projects);
  const projectBlocks = projectEntries
    .map(([name, project]) => generateProjectConfigBlock(name, project, tree))
    .join(',\n');

  return `${GENERATED_ESLINT_MARKER}
// @ts-check
const tsParser = require('@typescript-eslint/parser');
const angular = require('@angular-eslint/eslint-plugin');
const angularTemplate = require('@angular-eslint/eslint-plugin-template');
const angularTemplateParser = require('@angular-eslint/template-parser');
const {configs} = require('@isyfact/eslint-plugin');

module.exports = (async () => {
  const recommendedCfg = await configs.recommended();

  return [
    {ignores: ['**/node_modules/**', 'node_modules/', 'karma.conf.js', 'karma.config.js',  '**/*.server.ts', '**/server.ts']},

    ...recommendedCfg,
${projectBlocks},
  ];
})();
`;
}

/**
 * Installs @isyfact/eslint-plugin and related ESLint packages as devDependencies and
 * creates an eslint.config.js if none is present yet.
 * @param workspace The angular workspace configuration
 * @param context The schematic context used for logging
 * @param tree The virtual file system tree
 * @returns The updated tree
 */
function setupEslint(workspace: Workspace, context: SchematicContext, tree: Tree): Tree {
  addDevPackageToPackageJson(tree, '@isyfact/eslint-plugin', '^4.1.0');
  addDevPackageToPackageJson(tree, '@angular-eslint/eslint-plugin', '^21.0.0');
  addDevPackageToPackageJson(tree, '@angular-eslint/eslint-plugin-template', '^21.0.0');
  addDevPackageToPackageJson(tree, '@angular-eslint/template-parser', '^21.0.0');
  addDevPackageToPackageJson(tree, '@typescript-eslint/parser', '^8.0.0');
  addDevPackageToPackageJson(tree, 'eslint', '^9.0.0');

  context.logger.info('√ Added @isyfact/eslint-plugin and related ESLint packages to devDependencies.');

  addScriptToPackageJson(tree, 'lint', 'eslint .');
  context.logger.info('√ Added npm script "lint".');

  const monorepo = isMonorepo(workspace);
  context.logger.info(`√ Detected workspace type: ${monorepo ? 'Monorepo' : 'Simple project'}.`);

  if (tree.exists(ESLINT_CONFIG_PATH)) {
    return extendExistingEslintConfig(workspace, context, tree);
  }

  const configContent = generateEslintConfigContent(workspace, tree);
  tree.create(ESLINT_CONFIG_PATH, configContent);

  context.logger.info('√ Created eslint.config.js with IsyFact ESLint rules.');

  return tree;
}

/**
 * Installs @isyfact/prettier-plugin and prettier as devDependencies,
 * creates a .prettierrc.js and .prettierignore if not already present.
 * @param context The schematic context used for logging
 * @param tree The virtual file system tree
 * @returns The updated tree
 */
function setupPrettier(context: SchematicContext, tree: Tree): Tree {
  addDevPackageToPackageJson(tree, '@isyfact/prettier-plugin', '^1.0.0');
  addDevPackageToPackageJson(tree, 'prettier', '^3.0.0');
  context.logger.info('√ Added @isyfact/prettier-plugin and prettier to devDependencies.');

  addScriptToPackageJson(tree, 'format', 'prettier --write .');
  context.logger.info('√ Added npm script "format".');

  if (tree.exists(PRETTIER_CONFIG_PATH)) {
    context.logger.warn('⚠ Skipping .prettierrc.js creation: file already exists.');
  } else {
    tree.create(PRETTIER_CONFIG_PATH, `module.exports = require('@isyfact/prettier-plugin');\n`);
    context.logger.info('√ Created .prettierrc.js with IsyFact Prettier configuration.');
  }

  if (!tree.exists(PRETTIER_IGNORE_PATH)) {
    const pluginIgnore = tree.read('node_modules/@isyfact/prettier-plugin/.prettierignore');
    if (pluginIgnore) {
      tree.create(PRETTIER_IGNORE_PATH, pluginIgnore.toString('utf-8'));
      context.logger.info('√ Created .prettierignore from @isyfact/prettier-plugin.');
    }
  }

  return tree;
}

/**
 * Installs isy-angular-widgets as dependency and adds the necessary styles to the workspace.
 * @param options Schema options for the schematic
 * @returns Rule
 */
export function ngAdd(options: Schema): Rule {
  return (tree: Tree, context: SchematicContext) => {
    addTranslationFile(context, tree, 'de.json');
    addTranslationFile(context, tree, 'en.json');

    // Add necessary dependencies to new CLI project.

    addPackageToPackageJson(tree, '@angular/common', '^21.1.4');
    addPackageToPackageJson(tree, '@angular/core', '^21.1.4');
    addPackageToPackageJson(tree, 'primeicons', '^7.0.0');
    addPackageToPackageJson(tree, 'primeng', '^21.1.1');
    addPackageToPackageJson(tree, '@primeuix/themes', '^2.0.3');
    addPackageToPackageJson(tree, 'primeflex', '^4.0.0');

    // Install isy-angular-widgets
    context.addTask(new NodePackageInstallTask());

    const workspace = loadWorkspace(tree);

    if (options.addEslint) {
      setupEslint(workspace, context, tree);
    }

    if (options.addPrettier) {
      setupPrettier(context, tree);
    }

    applyStylesToWorkspace(workspace, context, tree);
    return applyAssetsToWorkspace(workspace, context, tree);
  };
}
function extendExistingEslintConfig(workspace: Workspace, context: SchematicContext, tree: Tree): Tree {
  const existingFile = tree.read(ESLINT_CONFIG_PATH);

  if (!existingFile) {
    throw new SchematicsException(`❌ Could not read ${ESLINT_CONFIG_PATH}.`);
  }

  const existingContent = existingFile.toString('utf-8');

  // Datei wurde bereits von unserem Schematic erzeugt -> neu generieren
  if (existingContent.includes(GENERATED_ESLINT_MARKER)) {
    if (tree.exists(ESLINT_BASE_CONFIG_PATH)) {
      tree.overwrite(ESLINT_CONFIG_PATH, generateWrappedEslintConfigContent(workspace, tree));
      context.logger.info(
        '√ Regenerated existing generated eslint.config.js wrapper with updated IsyFact ESLint configuration.'
      );
    } else {
      tree.overwrite(ESLINT_CONFIG_PATH, generateEslintConfigContent(workspace, tree));
      context.logger.info(
        '√ Regenerated existing generated eslint.config.js with updated IsyFact ESLint configuration.'
      );
    }

    return tree;
  }

  // Fremde bestehende Config -> sichern und Wrapper erzeugen
  if (!tree.exists(ESLINT_BASE_CONFIG_PATH)) {
    tree.create(ESLINT_BASE_CONFIG_PATH, existingContent);
    context.logger.info('√ Backed up existing eslint.config.js to eslint.config.base.js.');
  } else {
    context.logger.warn(
      '⚠ eslint.config.base.js already exists. Existing eslint.config.js was not modified automatically.'
    );
    return tree;
  }

  tree.overwrite(ESLINT_CONFIG_PATH, generateWrappedEslintConfigContent(workspace, tree));
  context.logger.info('√ Extended existing eslint.config.js with IsyFact ESLint configuration.');

  return tree;
}
function generateWrappedEslintConfigContent(workspace: Workspace, tree: Tree): string {
  const projectEntries = Object.entries(workspace.projects);
  const projectBlocks = projectEntries
    .map(([name, project]) => generateProjectConfigBlock(name, project, tree))
    .join(',\n');

  return `${GENERATED_ESLINT_MARKER}
    // @ts-check
    const tsParser = require('@typescript-eslint/parser');
    const angular = require('@angular-eslint/eslint-plugin');
    const angularTemplate = require('@angular-eslint/eslint-plugin-template');
    const angularTemplateParser = require('@angular-eslint/template-parser');
    const {configs} = require('@isyfact/eslint-plugin');
    const baseConfigModule = require('./eslint.config.base.js');

    module.exports = (async () => {
      const recommendedCfg = await configs.recommended();
      const resolvedBaseConfigModule = await Promise.resolve(baseConfigModule);
      const resolvedBaseConfig = resolvedBaseConfigModule?.default ?? resolvedBaseConfigModule;
      const normalizedBaseConfig = Array.isArray(resolvedBaseConfig) ? resolvedBaseConfig : [resolvedBaseConfig];

      return [
        ...normalizedBaseConfig,

        {ignores: ['**/node_modules/**', 'node_modules/', 'karma.conf.js', 'karma.config.js', '**/*.server.ts', '**/server.ts']},

        ...recommendedCfg,
    ${projectBlocks},
      ];
    })();
`;
}
