import {Rule, SchematicContext, SchematicsException, Tree} from '@angular-devkit/schematics';
import {NodePackageInstallTask} from '@angular-devkit/schematics/tasks';
import {addDevPackageToPackageJson, addPackageToPackageJson, addScriptToPackageJson} from './package-config';
import {Schema} from './schema';

interface AssetPatternObject {
  glob?: string;
  input: string;
  output?: string;
  ignore?: string[];
  followSymlinks?: boolean;
}

interface ArchitectOptions {
  styles?: string[];
  assets?: (string | AssetPatternObject)[];
  tsConfig?: string;
}

interface MyBuild {
  options: ArchitectOptions;
  configurations?: {
    development?: {tsConfig?: string};
  };
}

interface MyTest {
  options: {
    tsConfig?: string;
  };
}

interface Architect {
  build: MyBuild;
  test?: MyTest;
}

interface ProjectInfo {
  projectType: string;
  root: string;
  sourceRoot: string;
  prefix?: string;
  architect: Architect;
}

interface Workspace {
  projects: {
    [key: string]: ProjectInfo;
  };
}

const ESLINT_CONFIG_PATH = '/eslint.config.js';
const ESLINT_BASE_CONFIG_PATH = '/eslint.config.base.js';
const GENERATED_ESLINT_MARKER = '// generated by @isyfact/isy-angular-widgets';
const POSTCSS_CONFIG_PATH = '/.postcssrc.json';
const PRETTIER_CONFIG_PATH = '/.prettierrc.js';
const PRETTIER_IGNORE_PATH = '/.prettierignore';
const PRETTIER_IGNORE_CONTENT = `node_modules
dist
coverage
`;
const JSON_SPACES = 2;

/**
 * Normalizes a workspace-relative path to a Tree path.
 * @param path Workspace-relative path
 * @returns Normalized path starting with "/"
 */
function normalizeWorkspacePath(path: string): string {
  return path.startsWith('/') ? path : `/${path}`;
}

/**
 * Reads a file from the tree as text.
 * @param tree Virtual file tree
 * @param path File path
 * @returns File content as text
 * @throws {SchematicsException} If the file cannot be read
 */
function readFileAsText(tree: Tree, path: string): string {
  try {
    return tree.readText(normalizeWorkspacePath(path));
  } catch {
    throw new SchematicsException(`❌ Could not read file '${path}'.`);
  }
}

/**
 * Parses JSON text safely.
 * @param content JSON content
 * @param path File path used for error reporting
 * @returns Parsed JSON value
 * @throws {SchematicsException} If the JSON cannot be parsed
 */
function parseJson(content: string, path: string): unknown {
  try {
    return JSON.parse(content) as unknown;
  } catch {
    throw new SchematicsException(`❌ Could not parse JSON file '${path}'.`);
  }
}

/**
 * Derives the source root of a project.
 * @param project Project info
 * @returns Source root path without leading slash
 */
function getSourceRoot(project: ProjectInfo): string {
  if (project.sourceRoot) {
    return project.sourceRoot.replace(/^\/+/, '');
  }

  if (project.root) {
    return `${project.root}/src`;
  }

  return 'src';
}

/**
 * Derives the Tailwind entry file path for a project.
 * @param project Project info
 * @returns Workspace-relative Tailwind entry path
 */
function getTailwindEntryPath(project: ProjectInfo): string {
  return `${getSourceRoot(project)}/tailwind.css`;
}

/**
 * Creates a relative `@source` path from the Tailwind entry file to node_modules.
 * @param tailwindEntryPath Workspace-relative Tailwind entry file path
 * @returns Relative path to the isy-angular-widgets package
 */
function getLibrarySourcePathFromTailwindFile(tailwindEntryPath: string): string {
  const directoryDepth = tailwindEntryPath.split('/').filter(Boolean).length - 1;

  return `${'../'.repeat(directoryDepth)}node_modules/@isyfact/isy-angular-widgets`;
}

/**
 * Returns the application projects that should be configured.
 * If `options.project` is provided, only that project is returned.
 * Otherwise, all application projects are returned.
 * @param workspace The angular workspace configuration
 * @param options Schema options for the schematic
 * @returns The selected application projects
 * @throws {SchematicsException} If the requested project does not exist or is not an application
 */
function getTargetProjects(workspace: Workspace, options: Schema): [string, ProjectInfo][] {
  const applicationProjects = Object.entries(workspace.projects).filter(
    ([, project]) => project.projectType === 'application'
  );

  if (!options.project) {
    return applicationProjects;
  }

  const targetProject = applicationProjects.find(([name]) => name === options.project);

  if (!targetProject) {
    throw new SchematicsException(`❌ Project '${options.project}' was not found or is not an application project.`);
  }

  return [targetProject];
}

/**
 * Add necessary styles for isy-angular-widgets to the angular workspace.
 * @param workspace Current angular workspace object
 * @param context A rule factory, which is normally the way schematics are implemented. Returned by the tooling after loading a schematic description
 * @param tree List of styles
 * @param options Schema options for the schematic
 * @returns Tree Tree with styles
 */
function applyStylesToWorkspace(workspace: Workspace, context: SchematicContext, tree: Tree, options: Schema): Tree {
  const projects = getTargetProjects(workspace, options);
  let updatedProjects = 0;

  for (const [key, project] of projects) {
    if (!project.architect?.build?.options) {
      context.logger.warn(`⚠ Skipping add styles: Missing architect configuration on project ${key}.`);
      continue;
    }

    const tailwindEntryPath = getTailwindEntryPath(project);
    const styles = [
      tailwindEntryPath,
      'node_modules/primeicons/primeicons.css',
      'node_modules/@isyfact/isy-angular-widgets/assets/theme/isyfact-theme.scss'
    ];

    if (project.architect.build.options.styles) {
      const concatStyles = project.architect.build.options.styles.concat(styles);
      project.architect.build.options.styles = [...new Set(concatStyles)];
    } else {
      project.architect.build.options.styles = styles;
    }

    updatedProjects++;
    context.logger.info(`√ Added isy-angular-widgets styles to project '${key}'.`);
  }

  if (updatedProjects === 0) {
    context.logger.warn('⚠ Skipping add styles: Workspace does not contain any project of type application.');
    return tree;
  }

  tree.overwrite('/angular.json', JSON.stringify(workspace, null, JSON_SPACES));
  return tree;
}

/**
 * Derives the assets path for a project based on its configuration.
 * Prefers `sourceRoot` and falls back to `root/src/assets`.
 * @param project Project info
 * @returns The derived assets path
 */
function getAssetsPath(project: ProjectInfo): string {
  if (project.sourceRoot) {
    return `${project.sourceRoot}/assets`;
  }

  if (project.root) {
    return `${project.root}/src/assets`;
  }

  return 'src/assets';
}

/**
 * Adds the project-specific assets path to the assets array of each application project
 * found in the provided Angular workspace configuration. The assets path is derived from
 * the project's `sourceRoot` and falls back to `root/src/assets` if necessary.
 * If the assets array does not exist, it is initialized. If the derived assets path is
 * already present, no changes are made for that project.
 * @param workspace The Angular workspace configuration object.
 * @param context The schematic context used for logging and reporting.
 * @param tree The virtual file system tree representing the project files.
 * @param options Schema options for the schematic
 * @returns The updated virtual file system tree.
 */
function applyAssetsToWorkspace(workspace: Workspace, context: SchematicContext, tree: Tree, options: Schema): Tree {
  const projects = getTargetProjects(workspace, options);
  let updatedProjects = 0;

  for (const [key, project] of projects) {
    const buildOptions = project.architect?.build?.options;

    if (!buildOptions) {
      context.logger.warn(`⚠ Skipping assets update: Missing build options on project '${key}'.`);
      continue;
    }

    const assetsPath = getAssetsPath(project);
    const assetEntry: AssetPatternObject = {
      glob: '**/*',
      input: assetsPath,
      output: 'assets'
    };

    if (Array.isArray(buildOptions.assets)) {
      const hasAssets = buildOptions.assets.some((entry) =>
        typeof entry === 'string' ? entry === assetsPath : entry.input === assetsPath
      );

      if (!hasAssets) {
        buildOptions.assets.push(assetEntry);
        context.logger.info(`√ Added '${assetsPath}' to assets array of project '${key}'.`);
      }
    } else {
      buildOptions.assets = [assetEntry];
      context.logger.info(`√ Initialized assets array with '${assetsPath}' on project '${key}'.`);
    }

    updatedProjects++;
  }

  if (updatedProjects === 0) {
    context.logger.warn('⚠ Skipping assets update: No application project found.');
    return tree;
  }

  tree.overwrite('/angular.json', JSON.stringify(workspace, null, JSON_SPACES));
  return tree;
}

/**
 * Creates the Tailwind entry CSS file for each selected application project.
 * @param workspace Current angular workspace object
 * @param context Schematic context
 * @param tree Virtual file tree
 * @param options Schema options for the schematic
 */
function createTailwindEntryFiles(workspace: Workspace, context: SchematicContext, tree: Tree, options: Schema): void {
  const projects = getTargetProjects(workspace, options);

  for (const [projectName, project] of projects) {
    const tailwindEntryPath = getTailwindEntryPath(project);
    const librarySourcePath = getLibrarySourcePathFromTailwindFile(tailwindEntryPath);

    const tailwindFileContent = [
      '@layer theme, base, primeng, components, utilities, isyfact-theme;',
      '',
      '@import "tailwindcss/theme.css" layer(theme);',
      '@import "tailwindcss/preflight.css" layer(base);',
      '@import "tailwindcss/utilities.css" layer(utilities);',
      '',
      '@plugin "tailwindcss-primeui";',
      '',
      `@source "${librarySourcePath}";`,
      ''
    ].join('\n');

    const treePath = normalizeWorkspacePath(tailwindEntryPath);

    if (tree.exists(treePath)) {
      context.logger.info(`√ Tailwind entry file '${tailwindEntryPath}' already exists for project '${projectName}'.`);
    } else {
      tree.create(treePath, tailwindFileContent);
      context.logger.info(`√ Created Tailwind entry file '${tailwindEntryPath}' for project '${projectName}'.`);
    }
  }
}

/**
 * Creates or updates the PostCSS configuration required for Tailwind CSS v4.
 * @param context Schematic context
 * @param tree Virtual file tree
 */
function createPostCssConfig(context: SchematicContext, tree: Tree): void {
  const postCssConfig = {
    plugins: {
      '@tailwindcss/postcss': {}
    }
  };

  if (!tree.exists(POSTCSS_CONFIG_PATH)) {
    tree.create(POSTCSS_CONFIG_PATH, JSON.stringify(postCssConfig, null, JSON_SPACES));
    context.logger.info('√ Created .postcssrc.json.');
    return;
  }

  const existingContent = readFileAsText(tree, POSTCSS_CONFIG_PATH);
  const parsedConfig = parseJson(existingContent, POSTCSS_CONFIG_PATH) as {
    plugins?: Record<string, unknown>;
  };

  parsedConfig.plugins = parsedConfig.plugins ?? {};

  if (!('@tailwindcss/postcss' in parsedConfig.plugins)) {
    parsedConfig.plugins['@tailwindcss/postcss'] = {};
    tree.overwrite(POSTCSS_CONFIG_PATH, JSON.stringify(parsedConfig, null, JSON_SPACES));
    context.logger.info('√ Updated .postcssrc.json with @tailwindcss/postcss.');
  }
}

/**
 * Loads the angular workspace store in angular.json.
 * @param tree List with angular.json properties
 * @returns Workspace Part structure of angular.json file
 * @throws {SchematicsException} if workspace is not available
 */
function loadWorkspace(tree: Tree): Workspace {
  const workspaceConfig = readFileAsText(tree, '/angular.json');

  return parseJson(workspaceConfig, '/angular.json') as Workspace;
}

/**
 * Derives the i18n directory path for a project.
 * @param project Project info
 * @returns The derived i18n directory path
 */
function getI18nPath(project: ProjectInfo): string {
  if (project.sourceRoot) {
    return `${project.sourceRoot}/assets/i18n`;
  }

  if (project.root) {
    return `${project.root}/src/assets/i18n`;
  }

  return 'src/assets/i18n';
}

/**
 * Creates or merges a translation file for a target project.
 * @param context The schematic context used for logging
 * @param tree The virtual file system tree
 * @param projectName The project name
 * @param project The project info
 * @param language The translation file name
 * @throws {SchematicsException} If the source translation file cannot be found
 */
function addTranslationFileToProject(
  context: SchematicContext,
  tree: Tree,
  projectName: string,
  project: ProjectInfo,
  language: string
): void {
  const libraryTranslationPath = `/node_modules/@isyfact/isy-angular-widgets/assets/i18n/${language}`;
  const translationFilePath = `/${getI18nPath(project)}/${language}`;

  const isyTranslation = readFileAsText(tree, libraryTranslationPath);

  if (tree.exists(translationFilePath)) {
    const translation = readFileAsText(tree, translationFilePath);

    let translationJson = parseJson(translation, translationFilePath) as Record<string, unknown>;
    const isyTranslationJson = parseJson(isyTranslation, libraryTranslationPath) as Record<string, unknown>;

    translationJson = translationJson ? {...translationJson, ...isyTranslationJson} : isyTranslationJson;

    tree.overwrite(translationFilePath, JSON.stringify(translationJson, null, JSON_SPACES));
    context.logger.info(`√ Merged '${language}' into translation file of project '${projectName}'.`);
  } else {
    tree.create(translationFilePath, isyTranslation);
    context.logger.info(`√ Created '${language}' translation file for project '${projectName}'.`);
  }
}

/**
 * Creates or merges translation files for the selected application projects.
 * @param workspace The angular workspace configuration
 * @param context The schematic context used for logging
 * @param tree The virtual file system tree
 * @param options Schema options for the schematic
 */
function addTranslationFilesToWorkspace(
  workspace: Workspace,
  context: SchematicContext,
  tree: Tree,
  options: Schema
): void {
  const projects = getTargetProjects(workspace, options);
  let updatedProjects = 0;

  for (const [projectName, project] of projects) {
    addTranslationFileToProject(context, tree, projectName, project, 'de.json');
    addTranslationFileToProject(context, tree, projectName, project, 'en.json');
    updatedProjects++;
  }

  if (updatedProjects === 0) {
    context.logger.warn('⚠ Skipping translation update: No application project found.');
  }
}

/**
 * Returns the first existing candidate path from the workspace tree.
 * @param tree Virtual file tree
 * @param candidates Candidate paths relative to workspace root
 * @returns Existing path or null
 */
function resolveExistingPath(tree: Tree, candidates: string[]): string | null {
  for (const candidate of candidates) {
    if (tree.exists(normalizeWorkspacePath(candidate))) {
      return candidate;
    }
  }

  return null;
}

/**
 * Resolves the build tsconfig path for a project.
 * Uses angular.json first and falls back to common workspace paths.
 * @param project Project info
 * @param tree Virtual file tree
 * @returns tsconfig path or null
 */
function getBuildTsConfigPath(project: ProjectInfo, tree: Tree): string | null {
  const configuredBuildTsConfig =
    project.architect?.build?.options?.tsConfig ?? project.architect?.build?.configurations?.development?.tsConfig;

  if (configuredBuildTsConfig) {
    return configuredBuildTsConfig;
  }

  const projectRoot = project.root ? `${project.root}/` : '';

  return resolveExistingPath(tree, [`${projectRoot}tsconfig.app.json`, 'tsconfig.app.json']);
}

/**
 * Resolves the test tsconfig path for a project.
 * Uses angular.json first and falls back to common workspace paths.
 * @param project Project info
 * @param tree Virtual file tree
 * @returns tsconfig path or null
 */
function getTestTsConfigPath(project: ProjectInfo, tree: Tree): string | null {
  const configuredTestTsConfig = project.architect?.test?.options?.tsConfig;

  if (configuredTestTsConfig) {
    return configuredTestTsConfig;
  }

  const projectRoot = project.root ? `${project.root}/` : '';

  return resolveExistingPath(tree, [`${projectRoot}tsconfig.spec.json`, 'tsconfig.spec.json']);
}

/**
 * Determines whether the workspace is a monorepo (multiple projects each with their own subdirectory)
 * or a simple single-app project (root project located at the workspace root).
 * @param workspace The angular workspace configuration
 * @returns true if the workspace is a monorepo
 */
function isMonorepo(workspace: Workspace): boolean {
  return Object.values(workspace.projects).every((project) => project.root !== '');
}

/**
 * Generates JS code that merges all rule objects from configs.test.
 * This avoids applying the test config globally without project-aware parserOptions.
 * @returns JavaScript source string for merged test rules
 */
function generateMergedTestRulesExpression(): string {
  return `
        ...Object.assign(
          {},
          ...configs.test
            .filter((config) => config && typeof config === 'object' && config.rules)
            .map((config) => config.rules)
        )`;
}

/**
 * Generates a TypeScript/HTML config block for a single project to be embedded in eslint.config.js.
 * @param name Project name
 * @param project Project info
 * @param tree Virtual file tree
 * @returns JavaScript source string for the config blocks
 */
function generateProjectConfigBlock(name: string, project: ProjectInfo, tree: Tree): string {
  const sourceRoot = project.sourceRoot ?? 'src';
  const prefix = project.prefix ?? 'app';

  const buildTsConfig = getBuildTsConfigPath(project, tree);
  const testTsConfig = getTestTsConfigPath(project, tree) ?? buildTsConfig;

  const buildProjectList = buildTsConfig ? `'${buildTsConfig}'` : '';
  const testProjectList = testTsConfig ? `'${testTsConfig}'` : '';

  const mergedTestRules = generateMergedTestRulesExpression();

  return `
    // ${name}: TS
    {
      files: ['${sourceRoot}/**/*.ts'],
      ignores: ['${sourceRoot}/**/*.spec.ts'],
      languageOptions: {
        parser: tsParser,
        parserOptions: {
          project: [${buildProjectList}],
          tsconfigRootDir: __dirname,
          sourceType: 'module'
        }
      },
      plugins: {'@angular-eslint': angular},
      rules: {
        ...angular.configs.recommended.rules,
        '@angular-eslint/directive-selector': ['error', {type: 'attribute', prefix: '${prefix}', style: 'camelCase'}],
        '@angular-eslint/component-selector': ['error', {type: 'element', prefix: '${prefix}', style: 'kebab-case'}]
      }
    },
    // ${name}: Spec TS
    {
      files: ['${sourceRoot}/**/*.spec.ts'],
      languageOptions: {
        parser: tsParser,
        parserOptions: {
          project: [${testProjectList}],
          tsconfigRootDir: __dirname,
          sourceType: 'module'
        }
      },
      plugins: {'@angular-eslint': angular},
      rules: {
      ${mergedTestRules}
      }
    },
    // ${name}: HTML
    {
      files: ['${sourceRoot}/**/*.html'],
      languageOptions: {parser: angularTemplateParser},
      plugins: {'@angular-eslint/template': angularTemplate},
      rules: {...angularTemplate.configs.recommended.rules}
    },
    // ${name}: Inline Templates
    {
      files: ['${sourceRoot}/**/*.component.ts'],
      plugins: {
        '@angular-eslint': angular,
        '@angular-eslint/template': angularTemplate
      },
      processor: angularTemplate.processors['extract-inline-html']
    }`;
}

/**
 * Generates the content for eslint.config.js based on the workspace structure.
 * Supports both simple Angular projects and monorepos.
 * @param workspace The angular workspace configuration
 * @param tree The virtual file system tree
 * @returns The content of the eslint.config.js file as a string
 */
function generateEslintConfigContent(workspace: Workspace, tree: Tree): string {
  const projectEntries = Object.entries(workspace.projects);
  const projectBlocks = projectEntries
    .map(([name, project]) => generateProjectConfigBlock(name, project, tree))
    .join(',\n');

  return `${GENERATED_ESLINT_MARKER}
// @ts-check
const tsParser = require('@typescript-eslint/parser');
const angular = require('@angular-eslint/eslint-plugin');
const angularTemplate = require('@angular-eslint/eslint-plugin-template');
const angularTemplateParser = require('@angular-eslint/template-parser');
const {configs} = require('@isyfact/eslint-plugin');

module.exports = (async () => {
  const recommendedCfg = await configs.recommended();

  return [
    {ignores: ['**/node_modules/**', 'node_modules/', 'karma.conf.js', 'karma.config.js', '**/*.server.ts', '**/server.ts']},

    ...recommendedCfg,
${projectBlocks},
  ];
})();
`;
}

/**
 * Generates a wrapped eslint config that keeps an existing base config and appends the IsyFact config.
 * @param workspace The angular workspace configuration
 * @param tree The virtual file system tree
 * @returns The content of the wrapped eslint.config.js file
 */
function generateWrappedEslintConfigContent(workspace: Workspace, tree: Tree): string {
  const projectEntries = Object.entries(workspace.projects);
  const projectBlocks = projectEntries
    .map(([name, project]) => generateProjectConfigBlock(name, project, tree))
    .join(',\n');

  return `${GENERATED_ESLINT_MARKER}
    // @ts-check
    const tsParser = require('@typescript-eslint/parser');
    const angular = require('@angular-eslint/eslint-plugin');
    const angularTemplate = require('@angular-eslint/eslint-plugin-template');
    const angularTemplateParser = require('@angular-eslint/template-parser');
    const {configs} = require('@isyfact/eslint-plugin');
    const baseConfigModule = require('./eslint.config.base.js');

    module.exports = (async () => {
      const recommendedCfg = await configs.recommended();
      const resolvedBaseConfigModule = await Promise.resolve(baseConfigModule);
      const resolvedBaseConfig = resolvedBaseConfigModule?.default ?? resolvedBaseConfigModule;
      const normalizedBaseConfig = Array.isArray(resolvedBaseConfig) ? resolvedBaseConfig : [resolvedBaseConfig];

      return [
        ...normalizedBaseConfig,

        {ignores: ['**/node_modules/**', 'node_modules/', 'karma.conf.js', 'karma.config.js', '**/*.server.ts', '**/server.ts']},

        ...recommendedCfg,
    ${projectBlocks},
      ];
    })();
`;
}

/**
 * Extends an existing eslint.config.js or regenerates it when it was created by this schematic.
 * @param workspace The angular workspace configuration
 * @param context The schematic context used for logging
 * @param tree The virtual file system tree
 * @returns The updated tree
 */
function extendExistingEslintConfig(workspace: Workspace, context: SchematicContext, tree: Tree): Tree {
  const existingContent = readFileAsText(tree, ESLINT_CONFIG_PATH);

  if (existingContent.includes(GENERATED_ESLINT_MARKER)) {
    if (tree.exists(ESLINT_BASE_CONFIG_PATH)) {
      tree.overwrite(ESLINT_CONFIG_PATH, generateWrappedEslintConfigContent(workspace, tree));
      context.logger.info(
        '√ Regenerated existing generated eslint.config.js wrapper with updated IsyFact ESLint configuration.'
      );
    } else {
      tree.overwrite(ESLINT_CONFIG_PATH, generateEslintConfigContent(workspace, tree));
      context.logger.info(
        '√ Regenerated existing generated eslint.config.js with updated IsyFact ESLint configuration.'
      );
    }

    return tree;
  }

  if (tree.exists(ESLINT_BASE_CONFIG_PATH)) {
    context.logger.warn(
      '⚠ eslint.config.base.js already exists. Existing eslint.config.js was not modified automatically.'
    );
    return tree;
  }

  tree.create(ESLINT_BASE_CONFIG_PATH, existingContent);
  context.logger.info('√ Backed up existing eslint.config.js to eslint.config.base.js.');

  tree.overwrite(ESLINT_CONFIG_PATH, generateWrappedEslintConfigContent(workspace, tree));
  context.logger.info('√ Extended existing eslint.config.js with IsyFact ESLint configuration.');

  return tree;
}

/**
 * Installs `@isyfact/eslint-plugin` and related ESLint packages as devDependencies and
 * creates an eslint.config.js if none is present yet.
 * @param workspace The angular workspace configuration
 * @param context The schematic context used for logging
 * @param tree The virtual file system tree
 * @returns The updated tree
 */
function setupEslint(workspace: Workspace, context: SchematicContext, tree: Tree): Tree {
  addDevPackageToPackageJson(tree, '@isyfact/eslint-plugin', '^4.1.0');
  addDevPackageToPackageJson(tree, '@angular-eslint/eslint-plugin', '^21.0.0');
  addDevPackageToPackageJson(tree, '@angular-eslint/eslint-plugin-template', '^21.0.0');
  addDevPackageToPackageJson(tree, '@angular-eslint/template-parser', '^21.0.0');
  addDevPackageToPackageJson(tree, 'typescript-eslint', '^8.0.0');
  addDevPackageToPackageJson(tree, 'eslint', '^9.0.0');

  context.logger.info('√ Added @isyfact/eslint-plugin and related ESLint packages to devDependencies.');

  addScriptToPackageJson(tree, 'lint', 'eslint .');
  context.logger.info('√ Added npm script "lint".');

  const monorepo = isMonorepo(workspace);
  context.logger.info(`√ Detected workspace type: ${monorepo ? 'Monorepo' : 'Simple project'}.`);

  if (tree.exists(ESLINT_CONFIG_PATH)) {
    return extendExistingEslintConfig(workspace, context, tree);
  }

  const configContent = generateEslintConfigContent(workspace, tree);
  tree.create(ESLINT_CONFIG_PATH, configContent);

  context.logger.info('√ Created eslint.config.js with IsyFact ESLint rules.');

  return tree;
}

/**
 * Installs `@isyfact/prettier-plugin` and prettier as devDependencies,
 * creates a .prettierrc.js and .prettierignore if not already present.
 * @param context The schematic context used for logging
 * @param tree The virtual file system tree
 * @returns The updated tree
 */
function setupPrettier(context: SchematicContext, tree: Tree): Tree {
  addDevPackageToPackageJson(tree, '@isyfact/prettier-plugin', '^1.0.0');
  addDevPackageToPackageJson(tree, 'prettier', '^3.0.0');
  context.logger.info('√ Added @isyfact/prettier-plugin and prettier to devDependencies.');

  addScriptToPackageJson(tree, 'format', 'prettier --write .');
  context.logger.info('√ Added npm script "format".');

  if (tree.exists(PRETTIER_CONFIG_PATH)) {
    context.logger.warn('⚠ Skipping .prettierrc.js creation: file already exists.');
  } else {
    tree.create(PRETTIER_CONFIG_PATH, `module.exports = require('@isyfact/prettier-plugin');\n`);
    context.logger.info('√ Created .prettierrc.js with IsyFact Prettier configuration.');
  }

  if (!tree.exists(PRETTIER_IGNORE_PATH)) {
    tree.create(PRETTIER_IGNORE_PATH, PRETTIER_IGNORE_CONTENT);
    context.logger.info('√ Created .prettierignore from embedded template.');
  }

  return tree;
}

/**
 * Installs isy-angular-widgets as dependency and adds the necessary styles to the workspace.
 * @param options Schema options for the schematic
 * @returns Rule
 */
export function ngAdd(options: Schema): Rule {
  return (tree: Tree, context: SchematicContext) => {
    const workspace = loadWorkspace(tree);
    const targetProjects = getTargetProjects(workspace, options);

    context.logger.info(`√ Target projects: ${targetProjects.map(([name]) => name).join(', ')}.`);

    addTranslationFilesToWorkspace(workspace, context, tree, options);

    addPackageToPackageJson(tree, '@angular/common', '^21.1.4');
    addPackageToPackageJson(tree, '@angular/core', '^21.1.4');
    addPackageToPackageJson(tree, 'primeicons', '^7.0.0');
    addPackageToPackageJson(tree, 'primeng', '^21.1.3');
    addPackageToPackageJson(tree, '@primeuix/themes', '^2.0.3');
    addPackageToPackageJson(tree, 'tailwindcss-primeui', '^0.6.1');

    addDevPackageToPackageJson(tree, 'tailwindcss', '^4.2.4');
    addDevPackageToPackageJson(tree, '@tailwindcss/postcss', '^4.2.4');
    addDevPackageToPackageJson(tree, 'postcss', '^8.5.10');

    if (options.addEslint) {
      setupEslint(workspace, context, tree);
    }

    if (options.addPrettier) {
      setupPrettier(context, tree);
    }

    createTailwindEntryFiles(workspace, context, tree, options);
    createPostCssConfig(context, tree);

    applyStylesToWorkspace(workspace, context, tree, options);
    applyAssetsToWorkspace(workspace, context, tree, options);

    context.addTask(new NodePackageInstallTask());

    return tree;
  };
}
