= Konzept Angular
:navtitle: Konzept

*Angular Bibliothek / IT-System*

[cols="5m,2,3",options="header"]
|====
|Name |Art |Version

|isy-angular-widgets
|Bibliothek
|{page-component-display-version}
|====

Der Baustein Angular setzt die Anforderungen und Vorgaben der IsyFact, die im xref:isy-bedienkonzept-doc::bedienkonzept.adoc[Bedienkonzept] definiert sind, als https://isyfact.github.io/isy-angular-widgets/documentation/[Komponenten-Bibliothek icon:external-link[]^] um.
Die dazugehörige https://isyfact.github.io/isy-angular-widgets/[Referenzimplementierung icon:external-link[]^] stellt die Komponenten exemplarisch dar.
Der Baustein Angular stellt so eine einheitliche Umsetzung der GUIs in der gesamten Anwendungslandschaft sicher.

Dieses Konzept beschreibt alle Aspekte, die über das Bedienkonzept hinaus bei der Entwicklung eines Frontends zu berücksichtigen sind, um die definierten Anforderungen zu erfüllen.

[[grundlagen]]
== Grundlagen
include::documentation-guide::partial$content-new.adoc[]

[[anforderungen]]
== Anforderungen
include::documentation-guide::partial$content-new.adoc[]

////
[[definitionen]]
=== Definitionen

[[definition1]]
==== Definition1

[[definition2]]
==== Definition2

[[darstellung]]
=== Darstellung

[[eingabe]]
=== Eingabe

[[eingabewert1]]
==== Eingabewert1

[[eingabewert2]]
==== Eingabewert2

[[persistierung]]
=== Persistierung
////

[[vorgaben]]
== Vorgaben
include::documentation-guide::partial$content-new.adoc[]

////
Die folgenden architektonischen und technischen Vorgaben beziehen sich auf die Umsetzung der in Kapitel <<anforderungen>> genannten Anforderungen in der zu diesem Baustein gehörenden Bibliothek.

[[bedeutung-der-standardbibliothek]]
=== Bedeutung der Standardbibliothek

[[verwendung-der-standardbibliothek]]
=== Verwendung der Standardbibliothek

[[architekturvorgaben]]
=== Architekturvorgaben

[[technologieauswahl]]
==== Technologieauswahl

[[testunterstuetzung]]
==== Testunterstützung

[[querschnittliche-aspekte]]
== Querschnittliche Aspekte

[[fehlerbehandlung]]
=== Fehlerbehandlung

[[versionierung]]
=== Versionierung
////

