# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - '\d+.\d+.\d+'

env:
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
          path: |
            **/node_modules
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Validate latest changelog entry
        run: |
          FIRST_CHANGELOG_LINE=$(head -n 1 CHANGELOG.md)
          if [[ "$FIRST_CHANGELOG_LINE" =~ ^\#[[:space:]]${RELEASE_VERSION//./\\.}.* ]]; then
            echo "First changelog entry describes current version $RELEASE_VERSION"
          else
            echo "First changelog entry does not describe current version $RELEASE_VERSION."
            exit 1
          fi
      - name: Install dependencies
        run: npm ci
      - name: Check code formatting and linting
        run: |
          npm run prettier:check
          npm run lint
      - name: Run tests
        run: npm test
      - name: Build artifact
        run: npm run build
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: dist/isy-angular-widgets/

  sbom:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
          path: |
            **/node_modules
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Generate SBOM
        run: npx @cyclonedx/cyclonedx-npm --output-file isy-angular-widgets-sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: SBOM
          path: isy-angular-widgets-sbom.json

  publish-npm:
    needs: [build, sbom]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: Build
      - name: Download SBOM
        uses: actions/download-artifact@v4
        with:
          name: SBOM
      - name: Bump version in package.json
        run: |
          # jq can't replace file contents directly therefore a tmp file is needed
          tmp_file=$(mktemp)

          cp package.json "$tmp_file" \
            && jq --arg version "$RELEASE_VERSION" '.version=$version' "$tmp_file" >package.json \
            && rm -f "$tmp_file"
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
